---
title: "STAT 184 Homework Exercises" 
subtitle: "DataComputing Chapters 13 and 16"
author: "Anikate Ganju"
output: html_notebook
---

## Assigned Exercises

- DC Ch 12 Exercises: 13.1,13.2,16.1,16.2
## Front Matter

```{r}
# clean up workspace environment
rm(list = ls())

# all packages used for the assignment
library(tidyverse)
library(DataComputing)
library(ggplot2)
library(lubridate)
data("BabyNames")
```
## 13.1
```{r}
BabyNames %>% 
  group_by(name) %>%
  summarise(total = sum(count)) %>%
  filter( rank(desc(total)) <= 5)
```

## 13.2
1)
```{r}
Part1<-
BabyNames %>%
group_by(year, name) %>% #if you use group_by(name, year) then you will not get the same table
summarise(yearCount = sum(count)) %>%
mutate( nameRank = rank(desc(yearCount)), ranking = ifelse( nameRank <= 100, "Top_100", "Below") )

Part2<-
Part1 %>%
group_by(year, ranking) %>%
summarise(total = sum(yearCount)) %>%
arrange(desc(year))

View(Part1)
View(Part2)
```
2)
```{r}
frac <-
  Part1 %>%
  spread(key=ranking,value=yearCount) %>%
  mutate(ratio=sum(Top_100)/(sum(Below)+sum(Top_100)))

x <- sum(frac$Below, na.rm=FALSE)
y <- sum(frac$Top_100)
z <- (x+y)
ratio <- y/z
print(x) #not sure why this is not working.
View(frac)
```
3)
```{r}
frac %>%
  ggplot(aes(x=year,y=ratio)) #if I had 'ratio' working in 2) I think this would display something more useful
  geom_line() +
  theme_bw()
```

## 16.1
1)
```{r}
lubridate::mdy("April 30, 1777")-lubridate::mdy("July 31st, 1999")
```
2)
```{r}
lubridate::mdy("06-23-1912")-lubridate::mdy("July 31st, 1999")
```
3)
```{r}
lubridate::dmy("3 March 1847")-lubridate::mdy("July 31st, 1999")
```
4)
```{r}
lubridate::mdy("Nov. 11th, 1918")-lubridate::mdy("July 31st, 1999")
```
5)
```{r}
lubridate::mdy("July 20, 1969")-lubridate::mdy("July 31st, 1999")
```

## 16.2

1)readr::parse_number()
2)readr::parse_number()
3)none
4)readr::parse_number()
5)readr::parse_number()
6)readr::parse_number()
7)none
8)none
9)both
