---
title: "DC chpt 17"
author: "Anikate Ganju"
date: "11/17/2020"
output: html_notebook
---

## Chapter 17 DC: 17.1,17.2,17.3,17.4,17.5,17.8


# Set Up
```{r}
rm(list=ls())
```

```{r,message=FALSE}
# load necessary packages
library(tidyverse)
library(mosaic)
library(DataComputing)
library(ggplot2)
library(lubridate)
```

```{r}
# Load the BabyNames data into RStudio environment (from DataComputing package)
data("BabyNames")
```

```{r}
NameList <- 
  BabyNames %>% 
  group_by(name, sex) %>%
  summarise(total = sum(count)) 
```

## 17.1
```{r}
NameList %>%
  filter( grepl( "[aeiou]$", name ), sex=='M' ) %>%
  arrange(desc(total)) %>%
  head(10)
```

```{r}
NameList %>% 
  filter(grepl("[[:alpha:]] [[:space:]] [[:alpha:]]", name))
```

```{r}
NameList %>%
  filter( grepl( "joe$", name )) %>%
  arrange(desc(total)) %>%
  head(10)
```

## 17.2
```{r}
NameList %>%
  filter(grepl( "(k|c)[aeiou]*,[tl],[aeiou]*,n$", name )) %>%
  arrange(desc(total))
```

## 17.3
It seems like digits are being extracted from the string. Followed by special characters between short strings of numbers.

## 17.4
1) Considering all the or( | ) statsments in this string and []s, the pattern can only be 2 letters long.
2)none
3)A list of states

## 17.5
1)
```{r}
BibleNames <- 
  readr::read_csv("http://tiny.cc/dcf/BibleNames.csv")

BibleNames %>%
  filter( grepl( ".*(dam|lory|bar)", name )) %>%
  arrange(desc(name))
```
2)
```{r}
BibleNames %>%
  filter( grepl( "dam$|lory$|bar$", name )) %>%
  arrange(desc(name))
```

## 17.8
```{r}
CrimeSample <- 
  readr::read_csv("http://tiny.cc/dcf/Boston-Crimes-50.csv")
```
```{r}
View(CrimeSample)
```
```{r}
my_regex <- "[1234567890.]"

CrimeSample %>%
  tidyr::extract("Location", into=c("lat", "long"), 
                 regex = my_regex, 
                 convert = TRUE)
```

